version: "3.3"
services:
  jmeter:
    container_name: "jmeter"
    image: nonealexq/jmeter:5.4.3
    volumes:
      - ./:/mnt/jmeter
      - ./allure-results:/result/allure-results
    command: jmeter -n -t /mnt/jmeter/allure-jmeter-example.jmx -l /result/allure-results/result.jtl -j /result/jmeter.log
